name: 'get-azure-keyvault-secrets'
description:
  'Get all the Azure KeyVault Secrets and inject them as Environment variables
  for your github actions'
branding:
  icon: 'lock'
  color: 'blue'
inputs:
  keyvault_name:
    description: 'The name of the Azure KeyVault'
    required: true
  client_id:
    description: 'The Client ID of the Azure KeyVault'
    required: true
  client_secret:
    description: 'The Client Secret of the Azure KeyVault'
    required: true
  tenant_id:
    description: 'The Tenant ID of the Azure KeyVault'
    required: true
  separator:
    description:
      'The separator to use to separate the key and value of the secret'
    required: false
    default: '--'
runs:
  using: 'node20'
  main: 'dist/index.js'
